const SymbolData = {
  stock: [],
  forex: [
    {
      symbol: 'AUDUSD',
      description: '  AUD/USD',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'forex',
    },
    {
      symbol: 'EURJPY',
      description: 'EUR/JPY',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'forex',
    },
    {
      symbol: 'EURUSD',
      description: 'EUR/USD',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'forex',
    },
    {
      symbol: 'GBPJPY',
      description: 'GBP/JPY',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'forex',
    },
    {
      symbol: 'GBPUSD',
      description: 'GBP/USD',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'forex',
    },
    {
      symbol: 'USDCAD',
      description: 'USD/CAD',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'forex',
    },
    {
      symbol: 'USDCHF',
      description: 'USD/CHF',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'forex',
    },
    {
      symbol: 'USDJPY',
      description: 'USD/JPY',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'forex',
    },
  ],
  crypto: [],
  indixes: [
    {
      symbol: 'EUSTX50',
      description: 'EUSTX50',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'indixes',
    },
    {
      symbol: 'GER30',
      description: 'GER30',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'indixes',
    },
    {
      symbol: 'NAS100',
      description: 'NAS100',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'indixes',
    },
    {
      symbol: 'US30',
      description: 'US30',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'indixes',
    },
  ],
  commodities: [
    {
      symbol: 'SILBER',
      description: 'Silber',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'commodities',
    },
    {
      symbol: 'GOLD',
      description: 'Gold',
      icon: 'path/to/icon.png',
      source: 'MySQL',
      marketType: 'commodities',
    },
  ],
};

export default SymbolData;
